package momzzangseven.mztkbe.modules.web3.treasury.application.dto;

import momzzangseven.mztkbe.global.error.web3.TreasuryPrivateKeyInvalidException;
import momzzangseven.mztkbe.global.error.web3.Web3InvalidInputException;
import momzzangseven.mztkbe.modules.web3.treasury.domain.model.TreasuryRole;

/**
 * Input for {@code ProvisionTreasuryKeyUseCase}. Drives the KMS-backed provisioning flow:
 *
 * <ul>
 *   <li>{@code rawPrivateKey} — 32-byte secp256k1 private key (hex, optionally {@code 0x}-prefixed)
 *       generated by the operator out-of-band. The service derives the wallet address from it,
 *       wraps it for KMS {@code ImportKeyMaterial}, and zeroizes the value at the end of the
 *       transaction.
 *   <li>{@code role} — functional role of the wallet; the canonical alias is recovered via {@link
 *       TreasuryRole#toAlias()}.
 *   <li>{@code expectedAddress} — {@code 0x}-prefixed Ethereum address that the operator believes
 *       the {@code rawPrivateKey} corresponds to. The service derives the address itself and
 *       rejects the request with {@code TREASURY_WALLET_ADDRESS_MISMATCH} if the two do not match.
 *       Acts as a defence-in-depth check against fat-fingered key paste.
 * </ul>
 *
 * @param operatorUserId admin user id invoking the operation
 * @param rawPrivateKey 32-byte secp256k1 private key hex
 * @param role functional role binding for the new wallet
 * @param expectedAddress {@code 0x}-prefixed Ethereum address the operator expects
 */
public record ProvisionTreasuryKeyCommand(
    Long operatorUserId, String rawPrivateKey, TreasuryRole role, String expectedAddress) {

  public void validate() {
    if (operatorUserId == null || operatorUserId <= 0) {
      throw new Web3InvalidInputException("operatorUserId must be positive");
    }
    if (rawPrivateKey == null || rawPrivateKey.isBlank()) {
      throw new TreasuryPrivateKeyInvalidException("rawPrivateKey is required");
    }
    if (role == null) {
      throw new Web3InvalidInputException("role is required");
    }
    if (expectedAddress == null || expectedAddress.isBlank()) {
      throw new Web3InvalidInputException("expectedAddress is required");
    }
    if (!expectedAddress.startsWith("0x") || expectedAddress.length() != 42) {
      throw new Web3InvalidInputException("expectedAddress must be 0x-prefixed 40-hex");
    }
  }
}
