spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true                  # dev에서는 SQL 확인
    hibernate:
      ddl-auto: update              # dev에서만 허용
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul

kakao:
  auth:
    client: ${KAKAO_CLIENT_ID}
    redirect: http://localhost:3000/callback
  api:
    token-uri: https://kauth.kakao.com/oauth/token
    userinfo-uri: https://kapi.kakao.com/v2/user/me
google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: http://localhost:3000/callback
  api:
    token-uri: https://oauth2.googleapis.com/token
    userinfo-uri: https://openidconnect.googleapis.com/v1/userinfo

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health, info

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-here-must-be-at-least-32-characters-long}
  access-token-expiration: 900000      # 1 hour (in milliseconds)
  refresh-token-expiration: 604800000   # 7 days (in milliseconds)
  issuer: MZTK-BE
  audience: MZTK-Client
