package momzzangseven.mztkbe.modules.web3.qna.application.dto;

public enum QnaAdminReviewValidationCode {
  LOCAL_QUESTION_MISSING,
  LOCAL_QUESTION_NOT_QUESTION,
  LOCAL_QUESTION_NOT_OPEN,
  LOCAL_ANSWER_MISSING,
  LOCAL_ANSWER_POST_MISMATCH,
  LOCAL_ANSWER_ALREADY_ACCEPTED,
  ONCHAIN_QUESTION_MISSING,
  ONCHAIN_QUESTION_NOT_REFUNDABLE,
  ONCHAIN_ANSWER_MISSING,
  ONCHAIN_ANSWER_QUESTION_MISMATCH,
  ONCHAIN_ANSWER_ALREADY_ACCEPTED,
  QUESTION_HASH_MISMATCH,
  ANSWER_HASH_MISMATCH,
  ACTIVE_QUESTION_INTENT_PRESENT,
  ACTIVE_ANSWER_INTENT_PRESENT,
  SERVER_SIGNER_UNAVAILABLE,
  RELAYER_REGISTRATION_CHECK_FAILED,
  RELAYER_NOT_REGISTERED,
  INTERNAL_ISSUER_DISABLED,
  INTERNAL_ISSUER_SETTLE_DISABLED,
  INTERNAL_ISSUER_REFUND_DISABLED,
  ONCHAIN_QUESTION_HAS_ANSWERS
}
