package momzzangseven.mztkbe.modules.web3.execution.domain.vo;

public enum ExecutionActionTypeCode {
  TRANSFER_SEND,
  QNA_QUESTION_CREATE,
  QNA_ANSWER_SUBMIT,
  QNA_ANSWER_ACCEPT,
  QNA_QUESTION_CANCEL,
  QNA_ADMIN_SETTLE,
  QNA_ADMIN_REFUND,
  MARKETPLACE_CLASS_PURCHASE,
  MARKETPLACE_CLASS_CONFIRM,
  MARKETPLACE_CLASS_CANCEL,
  MARKETPLACE_ADMIN_SETTLE,
  MARKETPLACE_ADMIN_REFUND
}
