package momzzangseven.mztkbe.modules.web3.qna.infrastructure.persistence.adapter;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.UUID;
import momzzangseven.mztkbe.modules.web3.qna.application.port.out.ManageQnaAnswerExecutionIntentRefPort.QnaAnswerExecutionIntentRef;
import momzzangseven.mztkbe.modules.web3.qna.domain.vo.QnaExecutionActionType;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

@DisplayName("QnaAnswerExecutionIntentRefJdbcAdapter")
class QnaAnswerExecutionIntentRefJdbcAdapterTest {

  private JdbcTemplate jdbcTemplate;
  private QnaAnswerExecutionIntentRefJdbcAdapter adapter;

  @BeforeEach
  void setUp() {
    DriverManagerDataSource dataSource = new DriverManagerDataSource();
    dataSource.setDriverClassName("org.h2.Driver");
    dataSource.setUrl(
        "jdbc:h2:mem:"
            + UUID.randomUUID()
            + ";MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1");
    dataSource.setUsername("sa");
    dataSource.setPassword("");
    jdbcTemplate = new JdbcTemplate(dataSource);
    adapter = new QnaAnswerExecutionIntentRefJdbcAdapter(jdbcTemplate);
    jdbcTemplate.execute(
        """
        CREATE TABLE qna_answer_execution_intent_refs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            execution_intent_public_id VARCHAR(100) NOT NULL UNIQUE,
            post_id BIGINT NOT NULL,
            answer_id BIGINT NOT NULL,
            action_type VARCHAR(60) NOT NULL,
            status_snapshot VARCHAR(30),
            created_at TIMESTAMP,
            updated_at TIMESTAMP
        )
        """);
  }

  @Test
  @DisplayName("findByExecutionIntentId returns a matching ref")
  void findByExecutionIntentId_returnsMatchingRef() {
    insertRef("intent-1", 11L, 21L, QnaExecutionActionType.QNA_ANSWER_DELETE, "CONFIRMED");

    var result = adapter.findByExecutionIntentId("intent-1");

    assertThat(result).isPresent();
    assertThat(result.orElseThrow().postId()).isEqualTo(11L);
    assertThat(result.orElseThrow().answerId()).isEqualTo(21L);
    assertThat(result.orElseThrow().actionType())
        .isEqualTo(QnaExecutionActionType.QNA_ANSWER_DELETE);
  }

  @Test
  @DisplayName("findByPostIdAndActionType returns refs in newest id order")
  void findByPostIdAndActionType_returnsByPostAndAction() {
    insertRef("intent-1", 10L, 20L, QnaExecutionActionType.QNA_ANSWER_SUBMIT, "SIGNED");
    insertRef("intent-2", 10L, 21L, QnaExecutionActionType.QNA_ANSWER_SUBMIT, "SIGNED");
    insertRef("intent-3", 10L, 22L, QnaExecutionActionType.QNA_ANSWER_DELETE, "SIGNED");

    var result = adapter.findByPostIdAndActionType(10L, QnaExecutionActionType.QNA_ANSWER_SUBMIT);

    assertThat(result)
        .extracting(QnaAnswerExecutionIntentRef::executionIntentId)
        .containsExactly("intent-2", "intent-1");
  }

  private void insertRef(
      String executionIntentId,
      Long postId,
      Long answerId,
      QnaExecutionActionType actionType,
      String statusSnapshot) {
    jdbcTemplate.update(
        """
        INSERT INTO qna_answer_execution_intent_refs (
            execution_intent_public_id,
            post_id,
            answer_id,
            action_type,
            status_snapshot,
            created_at,
            updated_at
        ) VALUES (?, ?, ?, ?, ?, NOW(), NOW())
        """,
        executionIntentId,
        postId,
        answerId,
        actionType.name(),
        statusSnapshot);
  }
}
