package momzzangseven.mztkbe.modules.verification.domain.vo;

public enum FailureCode {
  EXTERNAL_AI_TIMEOUT,
  EXTERNAL_AI_UNAVAILABLE,
  EXTERNAL_AI_MALFORMED_RESPONSE,
  AI_RESPONSE_SCHEMA_INVALID,
  ORIGINAL_IMAGE_READ_FAILED,
  IMAGE_DECODE_FAILED,
  ANALYSIS_IMAGE_GENERATION_FAILED
}
