DROP TABLE IF EXISTS qna_answer_update_images;
DROP TABLE IF EXISTS qna_answer_update_states;
DROP TABLE IF EXISTS qna_answer_execution_intent_refs;
DROP TABLE IF EXISTS qna_question_update_states;

CREATE TABLE qna_answer_update_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    answer_id BIGINT NOT NULL REFERENCES answers(id) ON DELETE CASCADE,
    update_version BIGINT NOT NULL,
    update_token VARCHAR(100) NOT NULL,
    execution_intent_public_id VARCHAR(100),
    preparation_token VARCHAR(100),
    preparation_expires_at TIMESTAMP,
    status VARCHAR(40) NOT NULL,
    retryable BOOLEAN,
    error_code VARCHAR(120),
    error_reason VARCHAR(500),
    pending_content CLOB NOT NULL,
    expected_content_hash VARCHAR(66),
    reconciliation_required_reason VARCHAR(500),
    pending_image_update BOOLEAN NOT NULL DEFAULT FALSE,
    blocking_answer_id BIGINT GENERATED ALWAYS AS (
        CASE
            WHEN status IN (
                'PREPARING',
                'INTENT_BOUND',
                'PREPARATION_FAILED',
                'FAILED',
                'RECONCILIATION_REQUIRED'
            )
            THEN answer_id
            ELSE NULL
        END
    ),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qna_answer_update_states_answer_version UNIQUE (answer_id, update_version),
    CONSTRAINT uk_qna_answer_update_states_update_token UNIQUE (update_token),
    CONSTRAINT uk_qna_answer_update_states_execution_intent UNIQUE (execution_intent_public_id),
    CONSTRAINT uk_qna_answer_update_states_one_active UNIQUE (blocking_answer_id),
    CONSTRAINT ck_qna_answer_update_states_status
        CHECK (
            status IN (
                'PREPARING',
                'INTENT_BOUND',
                'PREPARATION_FAILED',
                'CONFIRMED',
                'FAILED',
                'STALE',
                'DISCARDED',
                'RECONCILIATION_REQUIRED'
            )
        )
);

CREATE INDEX idx_qna_answer_update_states_answer_status
    ON qna_answer_update_states(answer_id, status, created_at DESC);

CREATE INDEX idx_qna_answer_update_states_preparation_expiry
    ON qna_answer_update_states(status, preparation_expires_at);

CREATE TABLE qna_answer_update_images (
    update_state_id BIGINT NOT NULL REFERENCES qna_answer_update_states(id) ON DELETE CASCADE,
    image_id BIGINT NOT NULL REFERENCES images(id) ON DELETE CASCADE,
    image_order INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (update_state_id, image_id),
    CONSTRAINT uq_qna_answer_update_images_order UNIQUE (update_state_id, image_order),
    CONSTRAINT chk_qna_answer_update_images_order CHECK (image_order > 0)
);

CREATE INDEX idx_qna_answer_update_images_image
    ON qna_answer_update_images(image_id);

CREATE TABLE qna_answer_execution_intent_refs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_intent_public_id VARCHAR(100) NOT NULL,
    post_id BIGINT NOT NULL,
    answer_id BIGINT NOT NULL,
    action_type VARCHAR(60) NOT NULL,
    status_snapshot VARCHAR(30),
    local_outcome VARCHAR(40),
    local_outcome_reason VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qna_answer_execution_intent_refs_intent UNIQUE (execution_intent_public_id),
    CONSTRAINT ck_qna_answer_execution_intent_refs_action
        CHECK (action_type IN ('QNA_ANSWER_SUBMIT', 'QNA_ANSWER_UPDATE', 'QNA_ANSWER_DELETE'))
);

CREATE INDEX idx_qna_answer_execution_intent_refs_post_action
    ON qna_answer_execution_intent_refs(post_id, action_type);

CREATE INDEX idx_qna_answer_execution_intent_refs_answer_action
    ON qna_answer_execution_intent_refs(answer_id, action_type);

CREATE TABLE qna_question_update_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    requester_user_id BIGINT NOT NULL,
    update_version BIGINT NOT NULL,
    update_token VARCHAR(64) NOT NULL,
    expected_question_hash VARCHAR(66) NOT NULL,
    execution_intent_public_id VARCHAR(36),
    status VARCHAR(30) NOT NULL,
    preparation_retryable BOOLEAN NOT NULL DEFAULT TRUE,
    last_error_code VARCHAR(120),
    last_error_reason CLOB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qna_question_update_states_post_version UNIQUE (post_id, update_version),
    CONSTRAINT uk_qna_question_update_states_token UNIQUE (update_token),
    CONSTRAINT ck_qna_question_update_states_status
        CHECK (status IN ('PREPARING', 'PREPARATION_FAILED', 'INTENT_BOUND', 'CONFIRMED', 'STALE'))
);

CREATE UNIQUE INDEX uk_qna_question_update_states_intent_public_id
    ON qna_question_update_states(execution_intent_public_id);

CREATE INDEX idx_qna_question_update_states_post_latest
    ON qna_question_update_states(post_id, update_version DESC);

CREATE INDEX idx_qna_question_update_states_status_updated_at
    ON qna_question_update_states(status, updated_at);
