-- ============================================================
-- Core schemas include following tables: 
--
-- users, refresh_tokens, 
-- challenges
-- user_wallets,
-- xp_policies, xp_ledger,
-- user_progress, level_up_histories, level_policies, 
-- posts, comments, post_images,
-- locations, location_verifications,
-- attendance_logs
-- external_disconnect_tasks
-- ============================================================


-- ============================================================
-- SETTINGS
-- ============================================================
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

-- ============================================================
-- SCHEMAS
-- ============================================================

--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255),
    last_login_at timestamp(6) without time zone,
    nickname character varying(255),
    password_hash character varying(255),
    profile_image_url character varying(255),
    provider character varying(255) NOT NULL,
    provider_user_id character varying(255),
    role character varying(255) NOT NULL,
    status character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    wallet_address character varying(42),
    deleted_at timestamp(6) without time zone,
    google_refresh_token character varying(2048),
    CONSTRAINT users_provider_check CHECK (((provider)::text = ANY (ARRAY[('LOCAL'::character varying)::text, ('KAKAO'::character varying)::text, ('GOOGLE'::character varying)::text]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'TRAINER'::character varying, 'ADMIN'::character varying])::text[]))),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'BLOCKED'::character varying, 'DELETED'::character varying, 'UNVERIFIED'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    revoked_at timestamp(6) without time zone,
    token_hash character varying(500) NOT NULL,
    used_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);


--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: challenges; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.challenges (
    nonce character varying(36) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    message text NOT NULL,
    purpose character varying(50) NOT NULL,
    status character varying(20) NOT NULL,
    used_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    wallet_address character varying(42) NOT NULL,
    CONSTRAINT challenges_purpose_check CHECK (((purpose)::text = 'WALLET_REGISTRATION'::text)),
    CONSTRAINT challenges_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'USED'::character varying, 'EXPIRED'::character varying])::text[])))
);

--
-- Name: user_wallets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_wallets (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    registered_at timestamp(6) with time zone NOT NULL,
    status character varying(20) NOT NULL,
    unlinked_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone NOT NULL,
    user_deleted_at timestamp(6) with time zone,
    user_id bigint NOT NULL,
    wallet_address character varying(42) NOT NULL,
    CONSTRAINT user_wallets_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'UNLINKED'::character varying, 'USER_DELETED'::character varying, 'BLOCKED'::character varying, 'HARD_DELETED'::character varying])::text[])))
);


--
-- Name: user_wallets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_wallets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_wallets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: xp_policies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.xp_policies (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    daily_cap integer NOT NULL,
    effective_from timestamp(6) without time zone NOT NULL,
    effective_to timestamp(6) without time zone,
    enabled boolean NOT NULL,
    type character varying(50) NOT NULL,
    xp_amount integer NOT NULL,
    CONSTRAINT xp_policies_type_check CHECK (((type)::text = ANY ((ARRAY['CHECK_IN'::character varying, 'STREAK_7D'::character varying, 'WORKOUT'::character varying, 'POST'::character varying, 'COMMENT'::character varying])::text[])))
);


--
-- Name: xp_policies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.xp_policies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.xp_policies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: xp_ledger; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.xp_ledger (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    earned_on date NOT NULL,
    idempotency_key character varying(200) NOT NULL,
    occurred_at timestamp(6) without time zone NOT NULL,
    source_ref character varying(255),
    type character varying(20) NOT NULL,
    user_id bigint NOT NULL,
    xp_amount integer NOT NULL,
    CONSTRAINT xp_ledger_type_check CHECK (((type)::text = ANY ((ARRAY['CHECK_IN'::character varying, 'STREAK_7D'::character varying, 'WORKOUT'::character varying, 'POST'::character varying, 'COMMENT'::character varying])::text[])))
);


--
-- Name: xp_ledger_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.xp_ledger ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.xp_ledger_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: user_progress; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_progress (
    user_id bigint NOT NULL,
    available_xp integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    level integer NOT NULL,
    lifetime_xp integer NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);

--
-- Name: level_up_histories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.level_up_histories (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    from_level integer NOT NULL,
    level_policy_id bigint,
    reward_mztk integer NOT NULL,
    reward_status character varying(20) NOT NULL,
    reward_tx_hash character varying(66),
    spent_xp integer NOT NULL,
    to_level integer NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT level_up_histories_reward_status_check CHECK (((reward_status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: level_up_histories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.level_up_histories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.level_up_histories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: level_policies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.level_policies (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    effective_from timestamp(6) without time zone NOT NULL,
    effective_to timestamp(6) without time zone,
    enabled boolean NOT NULL,
    level integer NOT NULL,
    required_xp integer NOT NULL,
    reward_mztk integer NOT NULL
);


--
-- Name: level_policies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.level_policies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.level_policies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.posts (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_solved boolean NOT NULL,
    reward bigint,
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT posts_type_check CHECK (((type)::text = ANY ((ARRAY['FREE'::character varying, 'QUESTION'::character varying])::text[])))
);


--
-- Name: posts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comments (
    id bigint NOT NULL,
    content character varying(1000) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_deleted boolean NOT NULL,
    post_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    writer_id bigint NOT NULL,
    parent_id bigint
);


--
-- Name: comments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: post_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post_images (
    post_id bigint NOT NULL,
    image_urls character varying(255)
);

--
-- Name: locations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.locations (
    id bigint NOT NULL,
    address character varying(255) NOT NULL,
    deleted_at timestamp(6) with time zone,
    detail_address character varying(255),
    latitude double precision NOT NULL,
    location_name character varying(100) NOT NULL,
    longitude double precision NOT NULL,
    postal_code character varying(10) NOT NULL,
    registered_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: locations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.locations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.locations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: location_verifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.location_verifications (
    id bigint NOT NULL,
    current_latitude double precision NOT NULL,
    current_longitude double precision NOT NULL,
    distance double precision NOT NULL,
    is_verified boolean NOT NULL,
    location_id bigint,
    location_name character varying(100) NOT NULL,
    registered_latitude double precision NOT NULL,
    registered_longitude double precision NOT NULL,
    user_id bigint NOT NULL,
    verified_at timestamp with time zone NOT NULL
);


--
-- Name: location_verifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.location_verifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.location_verifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: attendance_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attendance_logs (
    id bigint NOT NULL,
    attended_date date NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: attendance_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attendance_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: external_disconnect_tasks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.external_disconnect_tasks (
    id bigint NOT NULL,
    attempt_count integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    encrypted_token character varying(2048),
    last_error character varying(4000),
    next_attempt_at timestamp(6) without time zone,
    provider character varying(255) NOT NULL,
    provider_user_id character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT external_disconnect_tasks_provider_check CHECK (((provider)::text = ANY ((ARRAY['LOCAL'::character varying, 'KAKAO'::character varying, 'GOOGLE'::character varying])::text[]))),
    CONSTRAINT external_disconnect_tasks_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: external_disconnect_tasks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.external_disconnect_tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.external_disconnect_tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- ============================================================
-- CONSTRAINTS
-- ============================================================

--
-- Name: attendance_logs attendance_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance_logs
    ADD CONSTRAINT attendance_logs_pkey PRIMARY KEY (id);


--
-- Name: challenges challenges_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.challenges
    ADD CONSTRAINT challenges_pkey PRIMARY KEY (nonce);


--
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


--
-- Name: external_disconnect_tasks external_disconnect_tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.external_disconnect_tasks
    ADD CONSTRAINT external_disconnect_tasks_pkey PRIMARY KEY (id);


--
-- Name: level_policies level_policies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.level_policies
    ADD CONSTRAINT level_policies_pkey PRIMARY KEY (id);


--
-- Name: level_up_histories level_up_histories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.level_up_histories
    ADD CONSTRAINT level_up_histories_pkey PRIMARY KEY (id);


--
-- Name: location_verifications location_verifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.location_verifications
    ADD CONSTRAINT location_verifications_pkey PRIMARY KEY (id);


--
-- Name: locations locations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_pkey PRIMARY KEY (id);


--
-- Name: posts posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: user_progress user_progress_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_progress
    ADD CONSTRAINT user_progress_pkey PRIMARY KEY (user_id);


--
-- Name: user_wallets user_wallets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_wallets
    ADD CONSTRAINT user_wallets_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: xp_ledger xp_ledger_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.xp_ledger
    ADD CONSTRAINT xp_ledger_pkey PRIMARY KEY (id);


--
-- Name: xp_policies xp_policies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.xp_policies
    ADD CONSTRAINT xp_policies_pkey PRIMARY KEY (id);


-- ============================================================
-- UNIQUE CONSTRAINTS
-- ============================================================

--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: level_up_histories uk7r42wcprfg1yqd2vo284l68su; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.level_up_histories
    ADD CONSTRAINT uk7r42wcprfg1yqd2vo284l68su UNIQUE (user_id, to_level);


--
-- Name: attendance_logs uk_attendance_user_date; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance_logs
    ADD CONSTRAINT uk_attendance_user_date UNIQUE (user_id, attended_date);


--
-- Name: users uk_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_email UNIQUE (email);


--
-- Name: users uk_provider_user; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_provider_user UNIQUE (provider, provider_user_id);


--
-- Name: user_wallets uk_user_wallets_address; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_wallets
    ADD CONSTRAINT uk_user_wallets_address UNIQUE (wallet_address);


--
-- Name: users uk_wallet_address; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_wallet_address UNIQUE (wallet_address);


--
-- Name: xp_ledger uka6plg6b7d0e5qsd30b1cj103j; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.xp_ledger
    ADD CONSTRAINT uka6plg6b7d0e5qsd30b1cj103j UNIQUE (user_id, idempotency_key);


--
-- Name: external_disconnect_tasks ukail0nsy6d8atq5qqd36gyfw2o; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.external_disconnect_tasks
    ADD CONSTRAINT ukail0nsy6d8atq5qqd36gyfw2o UNIQUE (user_id, provider);


--
-- Name: users ukh5ljnabobj9ni5t2p80vflge1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukh5ljnabobj9ni5t2p80vflge1 UNIQUE (provider_user_id);


--
-- Name: users ukieiivcpfkhqmium8o6xr9kkd1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukieiivcpfkhqmium8o6xr9kkd1 UNIQUE (provider, provider_user_id);


--
-- Name: xp_policies ukkkhn4cyiyj41lwbeetkeu8p99; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.xp_policies
    ADD CONSTRAINT ukkkhn4cyiyj41lwbeetkeu8p99 UNIQUE (type, effective_from);


--
-- Name: level_policies ukmt678c1q0n43092d57ielhxjd; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.level_policies
    ADD CONSTRAINT ukmt678c1q0n43092d57ielhxjd UNIQUE (level, effective_from);


--
-- Name: refresh_tokens uko2mlirhldriil2y7krapq4frt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT uko2mlirhldriil2y7krapq4frt UNIQUE (token_hash);


-- ============================================================
-- INDEXES
-- ============================================================

--
-- Name: idx6xf3b7h8xiuvtc5lcq5lh9kpw; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx6xf3b7h8xiuvtc5lcq5lh9kpw ON public.xp_ledger USING btree (user_id, type, earned_on);


--
-- Name: idx_attendance_user_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_attendance_user_date ON public.attendance_logs USING btree (user_id, attended_date DESC);


--
-- Name: idx_email; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_email ON public.users USING btree (email);


--
-- Name: idx_location_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_location_id ON public.location_verifications USING btree (location_id);


--
-- Name: idx_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_id ON public.location_verifications USING btree (user_id);


--
-- Name: idx_user_verified; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_verified ON public.location_verifications USING btree (user_id, verified_at DESC);


--
-- Name: idx_user_wallets_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_wallets_status ON public.user_wallets USING btree (status);


--
-- Name: idx_user_wallets_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_wallets_user_id ON public.user_wallets USING btree (user_id);


--
-- Name: idx_verified_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_verified_at ON public.location_verifications USING btree (verified_at DESC);


--
-- Name: idx_wallet_address; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_wallet_address ON public.users USING btree (wallet_address);


-- ============================================================
-- FOREIGN KEY CONSTRAINTS
-- ============================================================

--
-- Name: comments fklri30okf66phtcgbe5pok7cc0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fklri30okf66phtcgbe5pok7cc0 FOREIGN KEY (parent_id) REFERENCES public.comments(id);


--
-- Name: post_images fko1i5va2d8de9mwq727vxh0s05; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_images
    ADD CONSTRAINT fko1i5va2d8de9mwq727vxh0s05 FOREIGN KEY (post_id) REFERENCES public.posts(id);


--
-- PostgreSQL database dump complete
--