ALTER TABLE web3_treasury_keys
    ALTER COLUMN treasury_address DROP NOT NULL;

ALTER TABLE web3_treasury_keys
    ALTER COLUMN treasury_private_key_encrypted DROP NOT NULL;

ALTER TABLE web3_treasury_keys
    DROP CONSTRAINT IF EXISTS ck_web3_treasury_keys_singleton;

ALTER TABLE web3_treasury_keys
    ALTER COLUMN id DROP DEFAULT;

ALTER TABLE web3_treasury_keys
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

DO
$$
DECLARE
    seq_name TEXT;
    max_id   BIGINT;
BEGIN
    SELECT pg_get_serial_sequence('web3_treasury_keys', 'id') INTO seq_name;
    SELECT COALESCE(MAX(id), 0) INTO max_id FROM web3_treasury_keys;

    IF seq_name IS NULL THEN
        RETURN;
    END IF;

    IF max_id = 0 THEN
        EXECUTE format('SELECT setval(%L, 1, false)', seq_name);
    ELSE
        EXECUTE format('SELECT setval(%L, %s, true)', seq_name, max_id);
    END IF;
END
$$;

ALTER TABLE web3_treasury_keys
    ADD CONSTRAINT ck_web3_treasury_keys_slot_pair
        CHECK (
            (treasury_address IS NULL AND treasury_private_key_encrypted IS NULL)
            OR (treasury_address IS NOT NULL AND treasury_private_key_encrypted IS NOT NULL)
        );
