-- V051__create_trainer_sanctions_table.sql

CREATE TABLE trainer_sanctions (
    trainer_id       BIGINT PRIMARY KEY,
    strike_count     INT NOT NULL DEFAULT 0,
    suspended_until  TIMESTAMP,
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE trainer_strike_records (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainer_id       BIGINT NOT NULL REFERENCES trainer_sanctions(trainer_id),
    reason           VARCHAR(255) NOT NULL,
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_trainer_strike_records_trainer_id ON trainer_strike_records (trainer_id);
